### ISSUE TITLE
Q: support labels

### ISSUE THREAD

**Issue by basz** [hamburml/docker-flow-letsencrypt#27]
This is not supported in this repository, but wouldn't that be a convenient way to configure certificates? This way needed certificates configuration are defined within  your docker-compose file instead of in the letsencrypt docker-compose file.

https://github.com/n1b0r/docker-flow-proxy-letsencrypt/search?utf8=✓&q=com.df.letsencrypt&type=

**Comment by hamburml** [comment]
Thanks for your report.
You are not the first person who mentions this.

I chose the way of specifying the domains and subdomains directly on the docker-flow-letsencrypt container because this container creates the certificates and Let's Encrypt supports the creation of certs for a given second-level domain with up to 100 sub-domains. Let's Encrypt also has the rate limits for certificates registered per second-level domain and certs for sub-domains do also count to the limit for the second-level domain. See https://letsencrypt.org/docs/rate-limits/

If you for example try DF with another let's encrypt service and create a service 'test.domain.end' a certificate for domain.end is created which supports 'test.domain.end'. When you create another service for 'test2.domain.end' a new certificate for domain.end is created which supports 'test2.domain.end'. Your current certificates limit count is two. If you create lots of services this way you will reach the rate limit fairly easy. I know that you can store the certificates in a volume (and that's what this service also does) but I want to minimize the errors a user can have when using this container by forcing him to create the certificates directly on the letsencrypt service with the sub-domains a second-level domain can have. When you use DF with DFLE you create one certificate which works for 'domain.end', 'test.domain.end' and 'test2.domain.end' but your certificate limit count is one!

I hope everything was understandable. BTW: I used environment variables because it's fairly easy to use them in shell scripts.

BTW: Let's Encrypt will add wildcard-certificates which will make this great! https://letsencrypt.org/2017/07/06/wildcard-certificates-coming-jan-2018.html

**Comment by basz** [comment]
> I hope everything was understandable

:-)

**Comment by hamburml** [comment]
Closed. If you have any questions please reopen.
